import {UNITS,ROSTERS,BATTLEFIELD,MISSIONS,UNIT_CATALOG,FACTION_CATALOG,TACTICAL_CATALOG,rosterTotals} from './data.js';
import {runRosterBatch,simulateRoster} from './engine.js';
const $=s=>document.querySelector(s),pct=n=>(n*100).toFixed(1)+'%';
ROSTERS.terranMirror={...structuredClone(ROSTERS.terran),id:'terranMirror'};ROSTERS.protossMirror={...structuredClone(ROSTERS.protoss),id:'protossMirror'};
const keys=['zerg','terran','protoss','zergMirror','terranMirror','protossMirror'];
const baseEntries={zerg:UNIT_CATALOG.zerg.map(e=>({...e})),zergMirror:UNIT_CATALOG.zerg.map(e=>({...e})),terran:UNIT_CATALOG.terran.map(e=>({...e})),terranMirror:UNIT_CATALOG.terran.map(e=>({...e})),protoss:UNIT_CATALOG.protoss.map(e=>({...e})),protossMirror:UNIT_CATALOG.protoss.map(e=>({...e}))};
const raceOf=k=>k.replace('Mirror','');
const baseCards=Object.fromEntries(keys.map(k=>[k,TACTICAL_CATALOG[raceOf(k)].map(([name,gas])=>({name,gas}))]));
const counts={
 zerg:[1,0,1,0,0,0,0,0,2,0,0,0],
 zergMirror:[1,0,1,0,0,0,0,0,2,0,0,0],
 terran:[2,1,0,0,0,1,0],terranMirror:[2,1,0,0,0,1,0],protoss:[0,1,0,0,0,2,1],protossMirror:[0,1,0,0,0,2,1]
};
const defaultCounts=Object.fromEntries(Object.entries(counts).map(([k,v])=>[k,[...v]]));
const COMMUNITY_PRESETS={
 zerg:[{id:'roach-hydra',name:'Roach Wall · Hydra Snipe',counts:[1,0,1,0,0,0,0,0,2,0,0,0],faction:'케리건의 군단',cards:['부화장','대군주','바퀴 소굴','악성 점막'],upgrades:{0:['분쇄하는 발톱'],2:['가시 홈'],8:['땅굴 발톱','잠복 기습']},strategy:'바퀴와 여왕 계열의 피해 완화를 전선에 두고, 사거리 16″ 히드라가 후방에서 핵심 유닛을 제거합니다. 저글링은 마커 탈환과 측면 압박을 담당합니다.',source:'커뮤니티 1K Zerg 학습·탱키 전선 리스트를 현재 엔진 유닛으로 재구성'},
 {id:'ling-pressure',name:'Ling Pressure · Burrow',counts:[2,0,1,0,0,0,0,0,1,0,0,0],faction:'저그 군단',cards:['산란못','패스트 산란못','악성 점막'],upgrades:{0:['분쇄하는 발톱','아드레날린 분비선'],2:['가시 홈'],8:['잠복 기습']},strategy:'다수 저글링이 점막을 따라 빠르게 마커를 압박하고, 잠복 바퀴가 교전선을 흔듭니다. 히드라는 장갑 표적을 우선 사격합니다.',source:'커뮤니티의 다수 저글링·점막·잠복 운용 조언 기반'}],
 terran:[{id:'mmm',name:'1K Bio Fireline',counts:[2,0,0,0,0,1,0],faction:'테란 정규군',cards:['병영','공학 연구소','궤도 사령부'],upgrades:{0:['전투 방패','AGG-12'],5:['레이저 조준 시스템']},strategy:'해병은 Light 표적, 불곰은 Armoured 표적을 집중합니다. 여러 유닛이 같은 위치에서 사격선을 유지합니다. 원형 MMM의 의무관은 전투 프로필 연결 후 추가할 예정입니다.',source:'커뮤니티 추천 1K Marine–Marauder–Medic에서 엔진 연결 유닛만 반영'},
 {id:'ranged-line',name:'Marine · Goliath Gunline',counts:[2,1,1,0,0,1,0],faction:'테란 정규군',cards:['병영','군수 공장','공학 연구소'],upgrades:{0:['전투 방패'],1:['아레스급 목표물 설정 시스템'],5:['레이저 조준 시스템']},strategy:'중장거리 사격선을 만들고 골리앗과 불곰이 장갑 표적을 우선 제거합니다. 마커를 먼저 밟기보다 엄폐와 사거리를 유지합니다.',source:'커뮤니티의 Terran 기본 사격군·Goliath 스팸 조언 기반'}],
 protoss:[{id:'balanced',name:'Daelaam Balanced 1K',counts:[0,2,0,0,0,1,2],faction:'댈람',cards:['차원 분광기','황혼 의회','제련소'],upgrades:{1:['공명 파열포'],5:['그림자의 길']},strategy:'광전사가 전선을 묶고 사도와 추적자가 짧은 사격 각을 만듭니다. 원형 구성의 파수기는 전투 프로필 연결 후 추가할 예정입니다.',source:'커뮤니티 추천 2×Zealot · 2×Adept · Sentry · Stalker에서 엔진 연결 유닛만 반영'},
 {id:'stalker',name:'Stalker Position Play',counts:[0,1,0,0,0,3,2],faction:'댈람',cards:['차원 분광기','황혼 의회','관측선'],upgrades:{5:['그림자의 길','네라짐의 격노'],6:['각력 강화']},strategy:'추적자의 이동 기술과 16″ 사거리를 이용해 선제 사격 후 재배치합니다. 광전사는 돌입보다 추적자에게 접근하는 적을 차단합니다.',source:'커뮤니티의 Stalker·Twilight Council·Warp Prism 운용 조언 기반'}]
};
const activeStrategy=Object.fromEntries(keys.map(k=>[k,'사용자 구성']));
const KEYWORD_HELP={
 'burrowed':'BURROWED는 상태입니다. 해당 유닛은 HIDDEN을 얻고 Size가 0으로 취급되며, Disengage 판정의 Current Supply도 0으로 취급됩니다. 미션 목표를 점령하거나 경합할 수 없습니다.',
 '잠복':'BURROWED는 상태입니다. 해당 유닛은 HIDDEN을 얻고 Size가 0으로 취급되며, Disengage 판정의 Current Supply도 0으로 취급됩니다. 미션 목표를 점령하거나 경합할 수 없습니다.',
 'hidden':'HIDDEN 모델은 4″보다 멀리 있는 모델에게 보이지 않습니다. 4″ 이내에서는 일반 Line of Sight 규칙을 적용합니다.',
 '은신':'HIDDEN 모델은 4″보다 멀리 있는 모델에게 보이지 않습니다. 4″ 이내에서는 일반 Line of Sight 규칙을 적용합니다.',
 'coherency':'유닛을 재배치하는 행동이 끝날 때 모든 모델은 Leading Model의 3″ 안에 완전히 들어오고, 같은 유닛 모델을 통한 유효한 Coherency Link를 그릴 수 있어야 합니다. Coherency 밖인 유닛은 목표를 점령하거나 경합할 수 없습니다.',
 '코헤런시':'유닛을 재배치하는 행동이 끝날 때 모든 모델은 Leading Model의 3″ 안에 완전히 들어오고, 같은 유닛 모델을 통한 유효한 Coherency Link를 그릴 수 있어야 합니다. Coherency 밖인 유닛은 목표를 점령하거나 경합할 수 없습니다.',
 'supply':'Supply는 현재 남은 모델 수에 따라 변하는 값입니다. 배치 가능 여부, 목표 점령, Disengage의 Tactical Mass와 일부 승점 계산에 사용됩니다.',
 '서플라이':'Supply는 현재 남은 모델 수에 따라 변하는 값입니다. 배치 가능 여부, 목표 점령, Disengage의 Tactical Mass와 일부 승점 계산에 사용됩니다.',
 'tough':'TOUGH (X)는 Armour Roll에서 실패한 결과를 최대 X개 성공으로 바꿉니다.',
 'critical hit':'CRITICAL HIT (X)는 Armour Pool의 주사위 최대 X개를 Armour Roll 없이 Damage Pool로 옮깁니다.',
 'blocking terrain':'Effective Size 1 이상인 지형입니다. Cover 규칙에 따라 Line of Sight를 방해합니다.',
 'reserves':'모든 유닛은 Reserves에서 시작합니다. 배치 전에는 공격·능력의 대상이 될 수 없고 목표 점령에 참여하지 않으며, 전장 위 Total Supply에도 포함되지 않습니다.',
 '리저브':'모든 유닛은 Reserves에서 시작합니다. 배치 전에는 공격·능력의 대상이 될 수 없고 목표 점령에 참여하지 않으며, 전장 위 Total Supply에도 포함되지 않습니다.',
 'within':'Within은 모델 베이스 일부라도 범위에 닿으면 충족합니다. Wholly Within은 베이스 전체가 범위 안에 있어야 합니다.',
 'wholly within':'Wholly Within은 모델 베이스 전체가 지정 거리 안에 있어야 합니다. 일부만 걸치는 것은 충족하지 않습니다.',
 'tactical mass':'자신의 Current Supply가 교전 중인 모든 적 유닛의 합산 Current Supply보다 높으면 Tactical Mass를 가집니다. Disengage 후 다음 Assault Phase의 사격·Charge 제한을 무시합니다.',
 'mission marker':'미션 목표는 32mm 양면 마커입니다. 1·3은 Red, 2·4는 Blue, 5는 Neutral이며, 점령은 모델 수가 아니라 유효 Current Supply 합계로 판정합니다.'
 ,'available supply':'Available Supply는 현재 전장에 추가로 배치할 수 있는 Supply 여유를 뜻합니다. 유닛을 Reserves에서 배치할 때 해당 유닛의 Current Supply를 감당할 수 있어야 합니다.'
 ,'current supply':'Current Supply는 유닛에 남아 있는 모델 수에 따라 현재 적용되는 Supply 값입니다. 피해로 모델이 제거되면 달라질 수 있습니다.'
 ,'engaged':'Engaged는 모델이 적 모델의 Engagement Range 안에 있는 상태입니다. 교전 중인 유닛에는 이동·사격·Disengage 관련 제한이 적용됩니다.'
 ,'교전':'교전은 모델이 적 모델의 Engagement Range 안에 있는 상태입니다. 교전 중인 유닛에는 이동·사격·Disengage 관련 제한이 적용됩니다.'
 ,'disengage':'Disengage는 교전에서 벗어나는 이동입니다. 일반적으로 이후 Assault Phase의 사격과 Charge가 제한되며, Tactical Mass가 있으면 그 제한을 무시합니다.'
 ,'이탈':'Disengage는 교전에서 벗어나는 이동입니다. 일반적으로 이후 Assault Phase의 사격과 Charge가 제한되며, Tactical Mass가 있으면 그 제한을 무시합니다.'
 ,'visible':'Visible은 공격자 모델에서 대상 모델까지 Line of Sight를 그릴 수 있다는 뜻입니다. 지형·다른 모델·HIDDEN 같은 규칙이 가시성을 바꿀 수 있습니다.'
 ,'line of sight':'Line of Sight는 공격자와 대상 사이의 실제 시선을 확인하는 규칙입니다. Blocking Terrain과 모델이 시선을 가릴 수 있습니다.'
 ,'los':'LOS는 Line of Sight의 약자입니다. 공격자와 대상 사이의 실제 시선을 확인하며 Blocking Terrain과 모델이 이를 가릴 수 있습니다.'
 ,'flying':'FLYING 모델은 이동할 때 모델과 지형을 넘어갈 수 있지만, 이동을 끝낼 때 다른 모델이나 통과할 수 없는 위치와 겹칠 수 없습니다.'
 ,'비행':'FLYING 모델은 이동할 때 모델과 지형을 넘어갈 수 있지만, 이동을 끝낼 때 다른 모델이나 통과할 수 없는 위치와 겹칠 수 없습니다.'
 ,'modifier':'Modifier는 규칙이나 능력이 수치 또는 주사위 결과를 바꾸는 효과입니다. 서로 충돌하는 경우 Core Rules의 우선순위와 적용 순서를 따라야 합니다.'
 ,'repeatable':'REPEATABLE이 붙은 행동이나 능력은 해당 제한이 허용하는 범위에서 같은 활성화 또는 라운드에 다시 사용할 수 있습니다. 카드 문구의 조건을 함께 확인해야 합니다.'
};
const UPGRADE_CATALOG={
 zergling:[['잠복 기습',20],['분쇄하는 발톱',10],['아드레날린 분비선',20]],
 hydralisk:[['보조갑피',40],['숨기',20],['잠복 기습',40],['가시 홈',40]],
 roach:[['땅굴 발톱',10],['잠복 기습',20],['신경 재구성',20],['요오드화 담즙',10]],
 marine:[['전투 방패',30],['AGG-12',10],['로켓 발사기',40],['슬러그 쓰로워',20]],
 marauder:[['타소니스의 베테랑',30],['동역학 충격 완화복',40],['레이저 조준 시스템',40]],
 goliath:[['아레스급 목표물 설정 시스템',20],['확산 미사일',30],['폭주 미사일',40]],
 zealot:[['내 목숨을 아이어에',10],['각력 강화',20],['광전사의 원',10],['우리는 하나되어 싸운다',20]],
 stalker:[['그림자의 길',40],['네라짐의 격노',30]],
 adept:[['공명 파열포',20],['인도',10],['쐐기 타격',20]]
};
const selectedUpgrades=Object.fromEntries(keys.map(k=>[k,{}]));
const openPanel={};
let playerKey='zerg',opponentKey='terran',replayMode=false,selectedLogIndex=0,placementMode=false,selectedPlacement=null,placementLog=[],gameRunning=false,roundNumber=1,phaseIndex=0,activeSide='PLAYER',opponentTimer=null,activatedThisPhase=new Set;
const PHASES=[['MOVEMENT PHASE','배치 · 이동 · 이탈'],['ASSAULT PHASE','Run · Charge · 원거리 공격'],['COMBAT PHASE','교전 유닛 근접전'],['SCORING & CLEANUP','목표 점령 · 점수 · 정리']];
const resourceType={zerg:'BM',zergMirror:'BM',terran:'CP',terranMirror:'CP',protoss:'EN',protossMirror:'EN'};
const resourceYield={zerg:{'가속 점막':0,'패스트 산란못':2},zergMirror:{'가속 점막':0,'패스트 산란못':2},terran:{'전진 병영':2,'기술실 병영':2},terranMirror:{'전진 병영':2,'기술실 병영':2},protoss:{},protossMirror:{}};
function generatedResource(k){return 1+ROSTERS[k].tactical.reduce((n,c)=>n+(resourceYield[k][c.name]??1),0)}
function raceIcon(race){
  const r=race.toLowerCase();
  const marks={Zerg:'Z',Terran:'T',Protoss:'P'};
  return '<span class="race-icon '+r+'-icon" role="img" aria-label="'+race+' 추상 표식"><span>'+marks[race]+'</span></span>';
}
ROSTERS.zerg.faction='저그 군단';ROSTERS.zergMirror.faction='저그 군단';ROSTERS.terran.faction='테란 정규군';ROSTERS.terranMirror.faction='테란 정규군';ROSTERS.protoss.faction='칼라이';ROSTERS.protossMirror.faction='칼라이';
ROSTERS.zerg.tactical=[baseCards.zerg[3],baseCards.zerg[9]];ROSTERS.zergMirror.tactical=[baseCards.zergMirror[3],baseCards.zergMirror[9]];ROSTERS.terran.tactical=[baseCards.terran[2],baseCards.terran[7]];ROSTERS.terranMirror.tactical=[baseCards.terranMirror[2],baseCards.terranMirror[7]];ROSTERS.protoss.tactical=[baseCards.protoss[2],baseCards.protoss[7]];ROSTERS.protossMirror.tactical=[baseCards.protossMirror[2],baseCards.protossMirror[7]];
function rebuild(k){ROSTERS[k].entries=baseEntries[k].flatMap((e,i)=>Array.from({length:counts[k][i]},(_,n)=>({...e,label:e.label+(counts[k][i]>1?' #'+(n+1):'')})))}
function applyUpgradeCosts(k){baseEntries[k].forEach((e,i)=>{e.upgrades=[...(selectedUpgrades[k][i]||[])];e.upgradeCost=e.upgrades.reduce((sum,name)=>sum+(UPGRADE_CATALOG[e.unit]?.find(x=>x[0]===name)?.[1]||0),0)});rebuild(k)}
function upgradePickerHtml(k){const rows=baseEntries[k].map((e,i)=>{const options=UPGRADE_CATALOG[e.unit];if(!options||!counts[k][i])return'';return '<section class="upgrade-unit"><b>'+e.label+' 업그레이드</b><div class="upgrade-options">'+options.map(([name,cost])=>'<label><input type="checkbox" data-upgrade-key="'+k+'" data-upgrade-index="'+i+'" data-upgrade-name="'+name+'" '+((selectedUpgrades[k][i]||[]).includes(name)?'checked':'')+'><span>'+name+'</span><em>+'+cost+'M</em></label>').join('')+'</div></section>'}).join('');return '<div class="upgrade-picker"><h3>유닛 업그레이드</h3><p>공식 비용을 합산합니다. 전투 효과는 엔진 연결 항목만 적용됩니다.</p>'+rows+'</div>'}
function mountUpgradePickers(){for(const k of keys){if(openPanel[k]!=='units')continue;const host=k===playerKey?$('#leftRoster'):k===opponentKey?$('#rightRoster'):null,body=host?.querySelector('.flip-body');if(body&&!body.querySelector('.upgrade-picker'))body.insertAdjacentHTML('beforeend',upgradePickerHtml(k))}}
keys.forEach(rebuild);
function frontHtml(r,side,k){const t=rosterTotals(r),limit=+$('#points').value,res=resourceType[k];return '<div class="roster-content"><div class="roster-head"><div class="side-title"><span>'+side+'</span><button class="race-trigger" data-action="race" data-roster="'+k+'"><strong>'+raceIcon(r.race)+r.race+'</strong><i>⌄</i></button><small>'+r.name+'</small></div><div class="roster-actions"><button data-save-roster="'+k+'" title="이 로스터 저장" aria-label="'+r.race+' 로스터 저장">저장</button><button data-reset-roster="'+k+'" title="기본 로스터로 초기화" aria-label="'+r.race+' 로스터 초기화">↺</button><button data-action="units" data-roster="'+k+'" title="유닛 구성 변경">↻</button><button data-action="cards" data-roster="'+k+'" title="택티컬 카드 선택">▤</button></div></div><div class="economy resource-economy"><b>'+t.minerals+'<i>M</i></b><b>'+t.gas+'<i>G</i></b><b>'+generatedResource(k)+'<i>'+res+'</i></b><span>SUP '+t.supply+'</span><span>'+t.models+' models</span></div><div class="limit-meter"><i style="width:'+Math.min(100,t.minerals/limit*100)+'%"></i></div><button class="card-line faction-trigger" data-action="faction" data-roster="'+k+'"><span><small>FACTION · +1 '+res+'</small><strong>'+r.faction+'</strong></span><i>⌄</i></button><div class="tactics">'+(r.tactical.map(c=>'<span>'+c.name+'<b>'+c.gas+'G · +'+(resourceYield[k][c.name]??1)+res+'</b></span>').join('')||'<span>선택된 카드 없음</span>')+'</div><div class="squads">'+baseEntries[k].map((e,i)=>{const n=counts[k][i],u=UNITS[e.unit];return n?'<div class="squad '+(e.simReady?'':'pending-unit')+'"><div><strong>'+e.label+'</strong><small>'+(u?u.weapon.name+' · '+u.weapon.range+'” · RoA '+u.weapon.roa:e.role+' · 전투 데이터 연결 전')+'</small></div><b>×'+n+'</b><span>'+e.models*n+' models</span></div>':''}).join('')+'</div></div>'}

function resetRoster(k){counts[k]=[...defaultCounts[k]];selectedUpgrades[k]={};applyUpgradeCosts(k);const race=raceOf(k);ROSTERS[k].faction=race==='terran'?'테란 정규군':race==='protoss'?'칼라이':'저그 군단';const cardIndexes=race==='zerg'?[3,9]:[2,7];ROSTERS[k].tactical=cardIndexes.map(i=>baseCards[k][i]).filter(Boolean);activeStrategy[k]='사용자 구성';delete openPanel[k];render()}
function backHtml(action,k){const r=ROSTERS[k],title=action==='units'?'유닛 구성':action==='cards'?'택티컬 카드':action==='faction'?'팩션 선택':'종족 선택';let body='';if(action==='units')body=baseEntries[k].map((e,i)=>'<div class="editor-row '+(e.simReady?'':'pending-unit')+'"><span><strong>'+e.label+'</strong><small>'+e.role+' · '+e.models+' models · '+e.cost+'M'+(e.simReady?'':' · 전투 데이터 연결 전')+'</small></span><div class="modal-stepper"><button data-edit-key="'+k+'" data-edit-index="'+i+'" data-edit-delta="-1">−</button><b>'+counts[k][i]+'</b><button data-edit-key="'+k+'" data-edit-index="'+i+'" data-edit-delta="1">+</button></div></div>').join('');if(action==='cards')body='<p class="editor-help">종족별 전체 택티컬 카드입니다.</p>'+baseCards[k].map((c,i)=>'<label class="choice-row"><input type="checkbox" data-card-key="'+k+'" data-card-index="'+i+'" '+(r.tactical.some(x=>x.name===c.name)?'checked':'')+'><span><strong>'+c.name+'</strong><small>'+c.gas+'G</small></span></label>').join('');if(action==='faction')body=FACTION_CATALOG[raceOf(k)].map(name=>'<button class="choice-row '+(name===r.faction?'selected':'')+'" data-faction="'+name+'" data-faction-key="'+k+'"><span><strong>'+name+'</strong><small>팩션 카드</small></span><i>'+(name===r.faction?'✓':'›')+'</i></button>').join('');if(action==='race'){const current=raceOf(k);body=['zerg','terran','protoss'].map(x=>'<button class="choice-row '+(x===current?'selected':'')+'" data-race="'+x+'" data-race-side="'+(k===playerKey?'left':'right')+'"><span><strong>'+ROSTERS[x].race+'</strong><small>'+'이 종족으로 변경'+'</small></span><i>'+(x===current?'✓':'›')+'</i></button>').join('')}return '<div class="roster-content roster-back"><header><div><small>'+r.race.toUpperCase()+'</small><h2>'+title+'</h2></div><button class="flip-close" data-close-roster="'+k+'" title="로스터로 돌아가기">↶</button></header><div class="flip-body">'+body+'</div></div>'}
function editorBudget(action,k){if(action!=='units'&&action!=='cards')return'';const isUnits=action==='units',current=isUnits?rosterTotals(ROSTERS[k]).minerals:rosterTotals(ROSTERS[k]).gas,total=isUnits?+$('#points').value:100,unit=isUnits?'M':'G';return '<div class="editor-budget"><div><span>'+(isUnits?'유닛 비용':'택티컬 카드 비용')+'</span><b>현재 '+current+unit+' <i>/ 총 '+total+unit+'</i></b></div><div class="editor-budget-bar"><i style="width:'+Math.min(100,current/total*100)+'%"></i></div></div>'}
function presetHtml(k){const r=ROSTERS[k],items=COMMUNITY_PRESETS[raceOf(k)]||[];return '<div class="roster-content roster-back"><header><div><small>COMMUNITY · CURATED</small><h2>추천 로스터와 전략</h2></div><button class="flip-close" data-close-roster="'+k+'" title="로스터로 돌아가기">↶</button></header><div class="flip-body preset-list">'+items.map(p=>'<article class="preset-card"><div><strong>'+p.name+'</strong><small>'+p.source+'</small></div><p>'+p.strategy+'</p><button data-apply-preset="'+p.id+'" data-preset-key="'+k+'">이 구성 적용</button></article>').join('')+'<p class="editor-help">공개 커뮤니티의 초기 실전·이론 글을 바탕으로 정리했습니다. 대회 메타 순위가 아니라 검증할 전술 후보입니다.</p></div></div>'}
function rosterHtml(r,side,k){if(!openPanel[k])return frontHtml(r,side,k).replace('<button data-save-roster','<button data-action="presets" data-roster="'+k+'" title="커뮤니티 추천 로스터" aria-label="'+r.race+' 추천 로스터">★</button><button data-save-roster').replace('<div class="economy','<div class="strategy-strip"><b>'+activeStrategy[k]+'</b><span>전략 프리셋</span></div><div class="economy');if(openPanel[k]==='presets')return presetHtml(k);return backHtml(openPanel[k],k).replace('<div class="flip-body">','<div class="flip-body">'+editorBudget(openPanel[k],k))}
function applyCommunityPreset(k,id){const p=(COMMUNITY_PRESETS[raceOf(k)]||[]).find(x=>x.id===id);if(!p)return;counts[k]=[...p.counts];selectedUpgrades[k]=structuredClone(p.upgrades||{});ROSTERS[k].faction=p.faction;ROSTERS[k].tactical=baseCards[k].filter(c=>p.cards.includes(c.name));activeStrategy[k]=p.name;applyUpgradeCosts(k);delete openPanel[k];render()}
function replayTimeline(log){let round=0,html='<div class="replay-panel"><header><div><small>BATTLE REPLAY</small><h2>라운드 타임라인</h2></div><button data-replay-close aria-label="리플레이 닫기">×</button></header><div class="replay-scroll">';for(let i=0;i<log.length;i++){const e=log[i];if(e.type==='round'){round=e.round;html+='<button class="replay-round" data-log-round="'+round+'"><b>ROUND '+round+'</b><span>Movement · Assault · Combat · Score</span></button>';continue}if(e.type==='card')continue;const name=e.type==='move'?e.unit:e.type==='attack'?e.attacker+' → '+e.defender:'VP '+e.score.A+' : '+e.score.B;html+='<button class="replay-step '+e.type+'" data-log-index="'+i+'" data-round="'+round+'"><i>'+(e.type==='move'?'MOVE':e.type==='attack'?'FIRE':'SCORE')+'</i><span>'+name+'</span></button>'}return html+'</div></div>'}
function replayDetail(e,index){if(!e)return'<div class="replay-panel"><header><div><small>EVENT DETAIL</small><h2>상황을 선택하세요</h2></div></header></div>';const title=e.type==='move'?e.unit+' 이동':e.type==='attack'?e.attacker+' 공격':e.type==='score'?'라운드 점수':'카드 적용',body=e.type==='move'?'실제 이동 거리 '+e.distance.toFixed(1)+'″<br>위치 '+e.from.toFixed(1)+'″ → '+e.to.toFixed(1)+'″':e.type==='attack'?'대상 '+e.defender+'<br>거리 '+e.dist.toFixed(1)+'″ · 명중 '+e.hits+' · 피해 '+e.damage+' · 제거 '+e.casualties:e.type==='score'?'누적 VP '+e.score.A+' : '+e.score.B+'<br>마커 '+e.markers.join(' · '):e.effect;return '<div class="replay-panel detail"><header><div><small>SELECTED EVENT · #'+index+'</small><h2>'+title+'</h2></div><button data-replay-close aria-label="리플레이 닫기">×</button></header><div class="event-detail">'+body+'<div class="phase-note">현재 좌표는 엔진의 54″ 거리 계산값입니다. 배치 Supply·지형 충돌은 공식 카드 좌표 데이터 연결 대기 중입니다.</div></div></div>'}
function flip(k,action){const host=()=>k===playerKey?$('#leftRoster'):$('#rightRoster'),el=host();el.classList.add('flip-out');setTimeout(()=>{if(action)openPanel[k]=action;else delete openPanel[k];render();const fresh=host();fresh.classList.remove('flip-out');fresh.classList.add('flip-in');setTimeout(()=>fresh.classList.remove('flip-in'),220)},180)}
function logHtml(log,leftRace,enemyRace){let html='',round=0;for(let i=0;i<log.length;i++){const e=log[i];if(e.type==='round'){round=e.round;if(html)html+='</section>';html+='<section class="log-round"><h3 data-log-round="'+round+'"><span>ROUND</span>'+round+'<i class="round-races">'+raceIcon(leftRace)+'<small>VS</small>'+raceIcon(enemyRace)+'</i></h3>';continue}const id=e.attackerId||e.unitId||'',actor=id.startsWith('A-')?leftRace:id.startsWith('B-')?enemyRace:null,icon=actor?raceIcon(actor):'',tag='<div class="log-event '+(e.type==='attack'?'fire':e.type)+'" data-log-index="'+i+'" data-round="'+round+'">';if(e.type==='move')html+=tag+'<b>이동</b><span>'+icon+e.unit+'</span><em>'+e.from.toFixed(1)+'″ → '+e.to.toFixed(1)+'″</em></div>';else if(e.type==='card'){const cr=['Hydralisk Den','Spawning Pool'].includes(e.card)?'Zerg':['Barracks','Factory'].includes(e.card)?'Terran':'Protoss';html+=tag+'<b>카드</b><span>'+raceIcon(cr)+e.card+' → '+e.target+'</span><em>'+e.effect+'</em></div>'}else if(e.type==='score')html+=tag+'<b>점수</b><span>'+raceIcon(leftRace)+leftRace+' '+e.score.A+' : '+e.score.B+' '+raceIcon(enemyRace)+enemyRace+'</span><em>마커 '+e.markers.join(' / ')+'</em></div>';else html+=tag+'<b>공격</b><span>'+icon+e.attacker+' → '+e.defender+'</span><em>명중 '+e.hits+' · 피해 '+e.damage+' · 제거 '+e.casualties+'</em></div>'}return html+'</section>'}
let activeLog=[];
const mapY=x=>88-Math.max(0,Math.min(54,x))/54*76;
function mapLane(id='A-0'){const n=Number(id.split('-')[1])||0;return(id.startsWith('A-')?31:69)+(n%4-1.5)*5}
function point(x,y,color,label){return '<circle class="pulse" cx="'+x+'" cy="'+y+'" r="2.5" fill="'+color+'"/><circle cx="'+x+'" cy="'+y+'" r="1" fill="#fff"/><text x="'+(x+3)+'" y="'+(y-2)+'">'+label+'</text>'}
function modelCountAt(id,index=selectedLogIndex){let n=1;for(let i=0;i<=index;i++){const e=activeLog[i];if(e?.unitId===id&&e.models!=null)n=e.models;if(e?.defenderId===id&&e.remaining!=null)n=e.remaining}return n}
function activatedAt(id,index=selectedLogIndex){let round=0,start=0;for(let i=0;i<=index;i++)if(activeLog[i]?.type==='round'){round=activeLog[i].round;start=i}return activeLog.slice(start,index+1).some(e=>e.unitId===id||e.attackerId===id)}
function token(id,name,pos,models=null,ghost=false){if(models===true){ghost=true;models=null}const x=mapLane(id),y=mapY(pos),c=id.startsWith('A-')?'#81527e':'#477493',safe=name.replace(/#\d+/,'').trim(),n=Math.max(0,models??modelCountAt(id));let minis='',links='';for(let i=0;i<n;i++){const ring=i?Math.ceil(i/6):0,slot=i?((i-1)%6):0,angle=slot*Math.PI/3+(ring%2?Math.PI/6:0),radius=ring*.58,dx=Math.cos(angle)*radius,dy=Math.sin(angle)*radius;links+=i?'<line x1="'+x+'" y1="'+y+'" x2="'+(x+dx)+'" y2="'+(y+dy)+'"/>':'';minis+='<circle class="mini '+(i===0?'leader':'')+'" cx="'+(x+dx)+'" cy="'+(y+dy)+'" r=".29" fill="'+c+'"/>'}const activation=!ghost&&activatedAt(id)?'<g class="activation-token"><rect x="'+(x+1.25)+'" y="'+(y-2.35)+'" width="1.35" height="1.35" rx=".2"/><text x="'+(x+1.93)+'" y="'+(y-1.4)+'" text-anchor="middle">M</text></g>':'';return '<g class="unit-token '+(ghost?'ghost':'')+'"><circle class="coherency-boundary" cx="'+x+'" cy="'+y+'" r="1.9"/><g class="coherency-links">'+links+'</g>'+minis+'<text class="token-name" x="'+x+'" y="'+(y+.22)+'" text-anchor="middle">'+safe+'</text>'+activation+'</g>'}
function battlefieldState(index){const units=new Map;for(const e of activeLog){if(e.unitId&&!units.has(e.unitId))units.set(e.unitId,{id:e.unitId,name:e.unit,models:e.models||1,pos:e.unitId.startsWith('A-')?0:54});if(e.attackerId&&!units.has(e.attackerId))units.set(e.attackerId,{id:e.attackerId,name:e.attacker,models:1,pos:e.attackerId.startsWith('A-')?0:54});if(e.defenderId&&!units.has(e.defenderId))units.set(e.defenderId,{id:e.defenderId,name:e.defender,models:e.remaining+(e.casualties||0),pos:e.defenderId.startsWith('A-')?0:54})}for(let i=0;i<=index;i++){const e=activeLog[i];if(e?.type==='move'&&units.has(e.unitId)){units.get(e.unitId).pos=e.to;units.get(e.unitId).models=e.models||units.get(e.unitId).models}if(e?.type==='attack'&&units.has(e.defenderId))units.get(e.defenderId).models=e.remaining}return [...units.values()].filter(u=>u.models>0)}
function showEvent(index,el){const e=activeLog[index],svg=$('#eventOverlay'),cap=$('#eventCaption');if(!e)return;selectedLogIndex=index;document.querySelectorAll('[data-log-index].selected').forEach(x=>x.classList.remove('selected'));document.querySelectorAll('[data-log-index="'+index+'"]').forEach(x=>x.classList.add('selected'));el?.classList.add('selected');let art='',label='',ghost='';const state=battlefieldState(index);if(e.type==='move'){ghost=token(e.unitId,e.unit,e.from,true);const x=mapLane(e.unitId),y1=mapY(e.from),y2=mapY(e.to);art='<line class="track move-track" x1="'+x+'" y1="'+y1+'" x2="'+x+'" y2="'+y2+'" marker-end="url(#arrowBlue)"/>';label='이동 · '+e.unit+' · '+e.from.toFixed(1)+'″ → '+e.to.toFixed(1)+'″'}else if(e.type==='attack'){const x1=mapLane(e.attackerId),x2=mapLane(e.defenderId),y1=mapY(e.attackerX),y2=mapY(e.defenderX);art='<line class="track attack-track" x1="'+x1+'" y1="'+y1+'" x2="'+x2+'" y2="'+y2+'" marker-end="url(#arrowRed)"/>';label='공격 · '+e.attacker+' → '+e.defender+' · '+e.dist.toFixed(1)+'″ · 피해 '+e.damage}else if(e.type==='score'){art=[9,18,27,36,45].map((x,i)=>{const y=mapY(x),c=e.markers[i]==='A'?'#81527e':e.markers[i]==='B'?'#477493':'#68797a';return '<circle cx="50" cy="'+y+'" r="2.2" fill="'+c+'"/>'}).join('');label='라운드 점수 · '+e.score.A+' : '+e.score.B}else{cap.hidden=false;cap.textContent='카드 적용 · '+e.card+' → '+e.target;return}svg.innerHTML='<defs><marker id="arrowBlue" markerWidth="5" markerHeight="5" refX="4" refY="2.5" orient="auto"><path d="M0,0 L5,2.5 L0,5Z" fill="#72ceff"/></marker><marker id="arrowRed" markerWidth="5" markerHeight="5" refX="4" refY="2.5" orient="auto"><path d="M0,0 L5,2.5 L0,5Z" fill="#ff6f66"/></marker></defs>'+ghost+state.map(u=>token(u.id,u.name,u.pos)).join('')+art;cap.hidden=false;cap.textContent=label;if(replayMode)$('#rightRoster').innerHTML=replayDetail(e,index)}
function valid(left,enemy){const l=+$('#points').value,a=rosterTotals(left).minerals,b=rosterTotals(enemy).minerals,pending=left.entries.concat(enemy.entries).some(e=>!e.simReady||!UNITS[e.unit]),ok=a>0&&b>0&&a<=l&&b<=l&&!pending;$('#budgetStatus').className='budget-status '+(ok?'ok':'error');$('#budgetStatus').textContent='상한 '+l+' pt · '+left.race+' '+a+'M · '+enemy.race+' '+b+'M'+(pending?' · 전투 데이터 미연결 유닛 포함':ok?' · 미달 로스터 매칭 가능':' · 포인트 상한 초과 또는 빈 로스터');$('#run').disabled=!ok;return ok}
function render(){const left=ROSTERS[playerKey],enemy=ROSTERS[opponentKey],missionKey=$('#missionSelect').value,missionProfile=MISSIONS[missionKey]||MISSIONS.frontlines;$('#leftRoster').innerHTML=rosterHtml(left,'PLAYER · EDITABLE',playerKey);$('#rightRoster').innerHTML=rosterHtml(enemy,'OPPONENT · EDITABLE',opponentKey);if(!valid(left,enemy))return;const o={opponent:opponentKey,leftRoster:left,enemyRoster:enemy,mission:missionKey,maxRounds:missionProfile.rounds,games:Math.min(5000,Math.max(1,+$('#games').value)),seed:+$('#seed').value||42},batch=runRosterBatch(o),sample=simulateRoster(o);activeLog=sample.log;$('#missionLabel').textContent=missionProfile.name.toUpperCase()+' · MISSION MARKER ×5';$('#mission').textContent=missionProfile.name+' · 적용 중';$('#missionRule').textContent=missionProfile.rule;$('#stats').innerHTML='<div><span>'+left.race.toUpperCase()+' WIN</span><b>'+pct(batch.winRates.A)+'</b><small>평균 VP '+batch.averageVp.A.toFixed(1)+'</small></div><div><span>'+enemy.race.toUpperCase()+' WIN</span><b>'+pct(batch.winRates.B)+'</b><small>평균 VP '+batch.averageVp.B.toFixed(1)+'</small></div>';$('#barA').style.width=pct(batch.winRates.A);$('#barB').style.width=pct(batch.winRates.B);$('#log').innerHTML=logHtml(sample.log,left.race,enemy.race);if(replayMode){$('#leftRoster').innerHTML=replayTimeline(activeLog);$('#rightRoster').innerHTML=replayDetail(activeLog[selectedLogIndex],selectedLogIndex);$('#resultsTitle').textContent='전투 리플레이';$('#resultsHint').textContent='클릭하여 로스터로 돌아가기 ‹'}else{$('#resultsTitle').textContent='매치업 결과';$('#resultsHint').textContent='클릭하여 전투 리플레이 보기 ›'}$('#eventOverlay').innerHTML='';$('#eventCaption').hidden=true;const target=replayMode?$('#leftRoster [data-log-index="'+selectedLogIndex+'"]')||$('#leftRoster [data-log-index]'):null;if(target)showEvent(+target.dataset.logIndex,target);$('#comment').textContent=missionProfile.name+' 적용 결과, '+left.race+'의 '+enemy.race+'전 승률은 '+pct(batch.winRates.A)+'입니다.'}
document.addEventListener('click',e=>{const race=e.target.closest('[data-race-side]');if(!race||race.disabled)return;e.preventDefault();e.stopImmediatePropagation();const desired=race.dataset.race;if(race.dataset.raceSide==='left'){playerKey=desired;if(raceOf(opponentKey)===desired)opponentKey=desired+'Mirror'}else{opponentKey=raceOf(playerKey)===desired?desired+'Mirror':desired}Object.keys(openPanel).forEach(k=>delete openPanel[k]);render()},true);
document.addEventListener('click',e=>{if(e.target.closest('#matchupResults')){replayMode=!replayMode;if(replayMode){const lastScore=[...activeLog].map((x,i)=>[x,i]).filter(([x])=>x.type==='score').at(-1);if(lastScore)selectedLogIndex=lastScore[1]}render();return}if(e.target.closest('[data-replay-close]')){replayMode=false;render();return}const le=e.target.closest('[data-log-index]');if(le){showEvent(+le.dataset.logIndex,le);return}const rh=e.target.closest('[data-log-round]');if(rh){const steps=[...$('#leftRoster').querySelectorAll('[data-round="'+rh.dataset.logRound+'"]')];const last=steps.at(-1);if(last)showEvent(+last.dataset.logIndex,last);return}const reset=e.target.closest('[data-reset-roster]');if(reset){resetRoster(reset.dataset.resetRoster);return}const t=e.target.closest('[data-action]');if(t){flip(t.dataset.roster,t.dataset.action);return}const c=e.target.closest('[data-close-roster]');if(c){flip(c.dataset.closeRoster,null);return}const x=e.target.closest('[data-edit-delta]');if(x){const k=x.dataset.editKey,i=+x.dataset.editIndex,old=counts[k][i];counts[k][i]=Math.max(0,old+(+x.dataset.editDelta));rebuild(k);if(rosterTotals(ROSTERS[k]).minerals>+$('#points').value){counts[k][i]=old;rebuild(k)}render();return}const faction=e.target.closest('[data-faction]');if(faction){ROSTERS[faction.dataset.factionKey].faction=faction.dataset.faction;render();return}const race=e.target.closest('[data-race-side]');if(race&&!race.disabled){if(race.dataset.raceSide==='left')playerKey=race.dataset.race;else opponentKey=race.dataset.race==='zerg'&&playerKey==='zerg'?'zergMirror':race.dataset.race;Object.keys(openPanel).forEach(k=>delete openPanel[k]);render()}});
document.addEventListener('change',e=>{if(e.target.matches('[data-card-key]')){const k=e.target.dataset.cardKey,c=baseCards[k][+e.target.dataset.cardIndex];ROSTERS[k].tactical=e.target.checked?[...ROSTERS[k].tactical.filter(x=>x.name!==c.name),c]:ROSTERS[k].tactical.filter(x=>x.name!==c.name);render();return}if(e.target.matches('[data-upgrade-key]')){const k=e.target.dataset.upgradeKey,i=+e.target.dataset.upgradeIndex,name=e.target.dataset.upgradeName,current=new Set(selectedUpgrades[k][i]||[]);e.target.checked?current.add(name):current.delete(name);selectedUpgrades[k][i]=[...current];applyUpgradeCosts(k);render();mountUpgradePickers()}});
function saveState(){const state={version:1,playerKey,opponentKey,counts,selectedUpgrades,factions:Object.fromEntries(keys.map(k=>[k,ROSTERS[k].faction])),tactical:Object.fromEntries(keys.map(k=>[k,ROSTERS[k].tactical.map(c=>c.name)])),settings:{points:$('#points').value,games:$('#games').value,seed:$('#seed').value,mission:$('#missionSelect').value}};localStorage.setItem('starcraft-tmg-state',JSON.stringify(state));const b=$('#save');b.textContent='저장됨';b.classList.add('saved');setTimeout(()=>{b.textContent='저장';b.classList.remove('saved')},1200)}
function loadState(){try{const s=JSON.parse(localStorage.getItem('starcraft-tmg-state'));if(!s||s.version!==1)return;playerKey=s.playerKey||playerKey;opponentKey=s.opponentKey||opponentKey;for(const k of keys){if(s.counts?.[k])counts[k]=[...s.counts[k]];if(s.selectedUpgrades?.[k])selectedUpgrades[k]={...s.selectedUpgrades[k]};if(s.factions?.[k])ROSTERS[k].faction=s.factions[k];if(s.tactical?.[k])ROSTERS[k].tactical=baseCards[k].filter(c=>s.tactical[k].includes(c.name));applyUpgradeCosts(k)}if(s.settings){$('#points').value=s.settings.points||'1000';$('#games').value=s.settings.games||'1000';$('#seed').value=s.settings.seed||'42';$('#missionSelect').value=s.settings.mission||'frontlines'}}catch{localStorage.removeItem('starcraft-tmg-state')}}
function saveRosterState(k){const state={version:1,counts:[...counts[k]],selectedUpgrades:{...selectedUpgrades[k]},faction:ROSTERS[k].faction,tactical:ROSTERS[k].tactical.map(c=>c.name)};localStorage.setItem('starcraft-tmg-roster-'+k,JSON.stringify(state));const button=document.querySelector('[data-save-roster="'+k+'"]');if(button){button.classList.add('saved');button.setAttribute('aria-label',ROSTERS[k].race+' 로스터 저장됨');setTimeout(()=>{button.classList.remove('saved');button.setAttribute('aria-label',ROSTERS[k].race+' 로스터 저장')},1000)}}
function loadRosterStates(){for(const k of keys)try{const s=JSON.parse(localStorage.getItem('starcraft-tmg-roster-'+k));if(!s||s.version!==1)continue;if(s.counts)counts[k]=[...s.counts];if(s.selectedUpgrades)selectedUpgrades[k]={...s.selectedUpgrades};if(s.faction)ROSTERS[k].faction=s.faction;if(s.tactical)ROSTERS[k].tactical=baseCards[k].filter(c=>s.tactical.includes(c.name));applyUpgradeCosts(k)}catch{localStorage.removeItem('starcraft-tmg-roster-'+k)}}
document.addEventListener('click',e=>{const button=e.target.closest('[data-save-roster]');if(button){e.stopPropagation();saveRosterState(button.dataset.saveRoster)}});
document.addEventListener('click',e=>{const button=e.target.closest('[data-apply-preset]');if(button){e.stopPropagation();applyCommunityPreset(button.dataset.presetKey,button.dataset.applyPreset)}});
function updateMissionLayout(){const key=$('#missionSelect').value||'frontlines',profile=MISSIONS[key]||MISSIONS.frontlines;$('#mapWrap').dataset.layout=key;$('#mapTitle').textContent=profile.name+' · Lost Temple';$('#mapMeta').textContent=BATTLEFIELD.size+' · '+profile.rounds+' rounds · terrain preset';}
function advisorName(){return raceOf(playerKey)==='zerg'?'Abathur':raceOf(playerKey)==='terran'?'Adjutant':'Karax'}
function updateAdvisor(){const name=advisorName();$('#strategyChat h2').textContent=name+' · 전략 코치';document.querySelectorAll('#chatRoom .agent b').forEach(el=>el.textContent=name)}
function setChat(open){if(open)updateAdvisor();$('#strategyChat').classList.toggle('open',open);$('#strategyChat').setAttribute('aria-hidden',String(!open));$('#chatToggle').setAttribute('aria-expanded',String(open));$('#chatToggle i').textContent=open?'⌄':'⌃'}
const safeText=value=>String(value).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function localAgentReply(question){const left=ROSTERS[playerKey],enemy=ROSTERS[opponentKey],mission=MISSIONS[$('#missionSelect').value]||MISSIONS.frontlines,total=rosterTotals(left),q=question.toLowerCase(),units=left.entries.map(e=>e.label).join(', ');if(q.includes('m1')||q.includes('목표'))return '지도 숫자 1~5는 미션 목표물입니다. 목표 1·3은 Red, 목표 2·4는 Blue 친화 마커이고 목표 5는 중립으로 시작합니다. 실제 점령은 3″ 이내의 유효 Supply 비교로 결정됩니다.';if(q.includes('미션'))return mission.name+'에서는 '+mission.rule+' 현재 '+left.race+'는 '+activeStrategy[playerKey]+' 구성을 사용 중이므로, 초반에는 가까운 목표를 안전하게 확보하고 중반부터 고득점 목표에 전력을 집중하는 편이 좋습니다.';if(q.includes('상대')||q.includes(enemy.race.toLowerCase()))return enemy.race+'전에서는 사거리 밖에서 불필요하게 교환하지 말고, '+units+'의 역할을 나눠 한 표적에 화력을 집중하세요. 리플레이에서 먼저 손실되는 유닛을 확인한 뒤 전개 순서를 바꾸는 것이 좋습니다.';if(q.includes('로스터')||q.includes('운영')||q.includes('전략'))return left.race+' '+total.minerals+'M · SUP '+total.supply+' 로스터입니다. 핵심 전술은 '+activeStrategy[playerKey]+'입니다. '+units+' 순으로 역할을 구분하고, 전열 유닛은 목표와 적 사이에, 장거리 유닛은 벽 뒤 사선에 두세요.';return '현재 '+left.race+' 대 '+enemy.race+', '+mission.name+' 기준으로 분석 중입니다. 로스터 운영법, 상대 대응, 미션 목표 중 하나를 포함해 질문하면 더 구체적으로 답변합니다.'}
const CHAT_STORAGE_KEY='starcraft-tmg-chat-history';
function saveChatHistory(){const history=[...document.querySelectorAll('#chatRoom .chat-message[data-saved-chat]')].slice(-100).map(item=>({role:item.classList.contains('agent')?'agent':'user',message:item.querySelector('p')?.textContent||''}));localStorage.setItem(CHAT_STORAGE_KEY,JSON.stringify({version:1,history}))}
function loadChatHistory(){try{const saved=JSON.parse(localStorage.getItem(CHAT_STORAGE_KEY));if(!saved||saved.version!==1||!Array.isArray(saved.history))return;for(const item of saved.history.slice(-100))if((item.role==='agent'||item.role==='user')&&typeof item.message==='string')appendChat(item.role,item.message,false)}catch{localStorage.removeItem(CHAT_STORAGE_KEY)}}
function appendChat(role,message,persist=true){const item=document.createElement('div');item.className='chat-message '+role;item.dataset.savedChat='';item.innerHTML='<b>'+(role==='agent'?advisorName():'PLAYER')+'</b><p>'+safeText(message)+'</p>';$('#chatRoom').append(item);$('#chatRoom').scrollTop=$('#chatRoom').scrollHeight;if(persist)saveChatHistory()}
function keywordReply(question){const q=question.toLowerCase();for(const [keyword,definition] of Object.entries(KEYWORD_HELP))if(q.includes(keyword))return definition;const looksLikeRule=/키워드|용어|규칙|무슨 뜻|뜻이|what is|meaning/.test(q);return looksLikeRule?'해당 용어는 현재 검증된 Core Rules 용어집에 아직 연결되지 않았습니다. 영문 키워드 또는 카드에 적힌 문구를 그대로 입력해 주세요. 확인되지 않은 규칙은 추정해서 답하지 않습니다.':null}
function submitChat(e){e.preventDefault();const input=$('#chatInput'),question=input.value.trim();if(!question)return;appendChat('user',question);input.value='';setTimeout(()=>appendChat('agent',keywordReply(question)||localAgentReply(question)),180)}
function toggleMapFocus(){const focused=document.body.classList.toggle('map-focus');$('#mapWrap').setAttribute('aria-label',focused?'전장 집중 모드':'전장');$('#mapZoomToggle').classList.toggle('zoom-out',focused);$('#mapZoomToggle').setAttribute('aria-label',focused?'지도 축소':'지도 확대');$('#mapZoomToggle').title=focused?'지도 축소':'지도 확대'}
function showUnitBubble(e){const unit=e.target.closest?.('.unit-token');if(!unit)return;const name=unit.querySelector('.token-name')?.textContent||'Unit',models=unit.querySelectorAll('.mini').length,bubble=$('#unitBubble'),rect=$('#mapWrap').getBoundingClientRect();bubble.innerHTML='<b>'+safeText(name)+'</b><span>'+models+' models</span><div>'+Array.from({length:Math.min(models,18)},(_,i)=>'<i class="'+(i===0?'leader':'')+'"></i>').join('')+'</div>';bubble.style.left=Math.max(72,Math.min(rect.width-72,e.clientX-rect.left))+'px';bubble.style.top=Math.max(64,e.clientY-rect.top-18)+'px';bubble.hidden=false}
function hideUnitBubble(e){if(!e.relatedTarget?.closest?.('.unit-token'))$('#unitBubble').hidden=true}
function decorateRosters(){for(const [host,k] of [[$('#leftRoster'),playerKey],[$('#rightRoster'),opponentKey]]){host.dataset.race=raceOf(k);[...host.querySelectorAll('.squad')].forEach((row,index)=>{const entries=baseEntries[k].map((entry,i)=>({entry,i})).filter(x=>counts[k][x.i]);const item=entries[index];if(item){row.dataset.placementKey=k;row.dataset.placementIndex=item.i}})}}
function phaseName(){return PHASES[phaseIndex][0]}
function updatePhaseUi(){const playerTurn=activeSide==='PLAYER';$('#roundLabel').textContent=gameRunning?'ROUND '+roundNumber+' · PHASE '+(phaseIndex+1):'GAME READY';$('#phaseLabel').textContent=gameRunning?phaseName()+' · '+PHASES[phaseIndex][1]:'게임 시작 전';const b=$('#phasePass');b.disabled=!gameRunning||!playerTurn;b.textContent=!gameRunning?'게임 대기':playerTurn?'턴 넘기기':'상대 턴';$('#gameToggle').textContent=gameRunning?'게임 종료':'게임 시작'}
function clearRangeGuide(){const g=$('#rangeGuide');g.hidden=true;g.className='range-guide';g.removeAttribute('style');g.removeAttribute('data-label')}
function showDeployGuide(side,speed){const g=$('#rangeGuide'),h=speed/36*100;g.hidden=false;g.className='range-guide zone '+(side==='PLAYER'?'player-zone':'opponent-zone');g.style.height=h+'%';g.dataset.label='Entry Edge에서 최대 '+speed+'″'}
function showMoveGuide(p){const g=$('#rangeGuide');g.hidden=false;g.className='range-guide move-circle';g.style.left=p.x+'%';g.style.top=p.y+'%';g.style.width=p.speed/54*200+'%';g.style.height=p.speed/36*200+'%';g.dataset.label='Speed '+p.speed+'″'}
function eventTime(){return new Date().toLocaleTimeString('ko-KR',{hour:'2-digit',minute:'2-digit',second:'2-digit'})}
function resetGame(){clearTimeout(opponentTimer);gameRunning=false;placementMode=false;selectedPlacement=null;placementLog=[];activatedThisPhase.clear();roundNumber=1;phaseIndex=0;activeSide='PLAYER';document.body.classList.remove('placement-active');clearRangeGuide();render();$('#eventOverlay').innerHTML='';$('#resultsTitle').textContent='매치업 결과';$('#resultsHint').textContent='리플레이';updatePhaseUi()}
function toggleGame(){if(gameRunning){resetGame();return}gameRunning=true;placementMode=true;selectedPlacement=null;placementLog=[];activatedThisPhase.clear();roundNumber=1;phaseIndex=0;activeSide='PLAYER';replayMode=false;document.body.classList.add('placement-active');render();$('#eventOverlay').innerHTML='';$('#resultsTitle').textContent='실시간 게임 기록';$('#resultsHint').textContent='Movement Phase · 리저브 유닛 선택';$('#stats').innerHTML='<div class="placement-note">모든 유닛은 리저브에서 시작합니다. Deploy는 Entry Edge에서 Speed만큼 이동해 끝내며, 각 유닛은 한 Phase에 한 번만 활성화됩니다.</div>';decorateRosters();updatePhaseUi()}
function selectPlacement(row){if(!gameRunning||phaseIndex!==0||activeSide!=='PLAYER')return;const k=row.dataset.placementKey,i=+row.dataset.placementIndex;if(k!==playerKey)return;const e=baseEntries[k][i],already=placementLog.filter(p=>p.key===k&&p.index===i&&!p.removed).length;if(already>=counts[k][i]){$('#resultsHint').textContent=e.label+'은 모두 배치되었습니다';return}document.querySelectorAll('.squad.placement-selected').forEach(x=>x.classList.remove('placement-selected'));row.classList.add('placement-selected');const u=UNITS[e.unit],speed=u?.speed||0;selectedPlacement={id:'P-'+i+'-'+already,key:k,index:i,side:'PLAYER',race:ROSTERS[k].race,label:e.label+(counts[k][i]>1?' #'+(already+1):''),models:e.models,speed};showDeployGuide('PLAYER',speed);$('#resultsHint').textContent=e.label+' · Entry Edge에서 최대 '+speed+'″'}
function placementArt(p){const color=p.race==='Zerg'?'#8e638f':p.race==='Terran'?'#557fa0':'#c3a45f',shown=Math.min(p.models,12),dots=Array.from({length:shown},(_,i)=>{const a=i*Math.PI*2/shown,r=shown===1?0:1.5;return '<circle cx="'+(p.x+Math.cos(a)*r)+'" cy="'+(p.y+Math.sin(a)*r)+'" r=".75" fill="'+color+'"/>'}).join('');return '<g class="manual-placement selectable" data-placement-id="'+p.id+'">'+dots+'<text x="'+p.x+'" y="'+(p.y+3.4)+'" text-anchor="middle">'+safeText(p.label)+'</text></g>'}
function redrawPlacements(){const svg=$('#eventOverlay');svg.innerHTML=placementLog.map(placementArt).join('')}
function validDeployY(side,y,speed){const reach=speed/36*100;return side==='PLAYER'?y>=100-reach:y<=reach}
function moveSelected(p,x,y){const dx=(x-p.x)*54/100,dy=(y-p.y)*36/100,d=Math.hypot(dx,dy);if(d>p.speed+.01)return false;p.from={x:p.x,y:p.y};p.x=x;p.y=y;p.time=eventTime();p.action='MOVE '+d.toFixed(1)+'″';return true}
function placeSelected(e){if(!gameRunning||!selectedPlacement||e.target.closest('#mapZoomToggle,.manual-placement'))return;const rect=$('#mapWrap').getBoundingClientRect(),x=(e.clientX-rect.left)/rect.width*100,y=(e.clientY-rect.top)/rect.height*100;if(selectedPlacement.existing){const acted=selectedPlacement.existing;if(!moveSelected(acted,x,y)){illegalPlacement('Speed '+acted.speed+'″ 밖입니다');return}redrawPlacements();finishPlayerActivation(acted.id);return}if(!validDeployY(selectedPlacement.side,y,selectedPlacement.speed)){illegalPlacement('Entry Edge에서 '+selectedPlacement.speed+'″ 안에 배치해야 합니다');return}const p={...selectedPlacement,x,y,time:eventTime(),action:'DEPLOY'};placementLog.push(p);redrawPlacements();finishPlayerActivation(p.id)}
function illegalPlacement(message){$('#resultsHint').textContent=message;$('#mapWrap').classList.remove('placement-error');requestAnimationFrame(()=>$('#mapWrap').classList.add('placement-error'))}
function finishPlayerActivation(id){activatedThisPhase.add(id);selectedPlacement=null;clearRangeGuide();document.querySelectorAll('.squad.placement-selected').forEach(x=>x.classList.remove('placement-selected'));renderPlacementFeed();activeSide='OPPONENT';updatePhaseUi();opponentTimer=setTimeout(opponentActivation,650)}
function opponentActivation(){if(!gameRunning)return;if(phaseIndex===0){const candidates=baseEntries[opponentKey].map((e,i)=>({e,i})).filter(({i})=>placementLog.filter(p=>p.key===opponentKey&&p.index===i).length<counts[opponentKey][i]);const c=candidates[0];if(c){const n=placementLog.filter(p=>p.key===opponentKey&&p.index===c.i).length,u=UNITS[c.e.unit],speed=u?.speed||0,p={id:'O-'+c.i+'-'+n,key:opponentKey,index:c.i,side:'OPPONENT',race:ROSTERS[opponentKey].race,label:c.e.label+(counts[opponentKey][c.i]>1?' #'+(n+1):''),models:c.e.models,speed,x:18+((c.i*23+n*17)%64),y:Math.max(1,speed/36*50),time:eventTime(),action:'DEPLOY · AI'};placementLog.push(p);activatedThisPhase.add(p.id);redrawPlacements()}}activeSide='PLAYER';renderPlacementFeed();updatePhaseUi()}
function renderPlacementFeed(){$('#resultsTitle').textContent='실시간 게임 기록 · '+placementLog.length;$('#resultsHint').textContent=activeSide==='PLAYER'?'내 활성화':'상대 활성화';$('#stats').innerHTML='<div class="placement-feed">'+placementLog.slice().reverse().map(p=>'<small>'+p.time+' · '+p.side+' · '+p.action+' · '+p.label+' · X '+p.x.toFixed(1)+' / Y '+p.y.toFixed(1)+'</small>').join('')+'</div>'}
function passTurn(){if(!gameRunning||activeSide!=='PLAYER')return;activeSide='OPPONENT';updatePhaseUi();$('#resultsHint').textContent='내 Pass 완료 · 상대는 남은 활성화 또는 Pass';opponentTimer=setTimeout(()=>{phaseIndex++;activatedThisPhase.clear();if(phaseIndex>=PHASES.length){phaseIndex=0;roundNumber++;if(roundNumber>5){resetGame();return}}activeSide='PLAYER';placementMode=phaseIndex===0;selectedPlacement=null;clearRangeGuide();updatePhaseUi();$('#resultsHint').textContent='상대 Pass · '+phaseName()+' 시작'},700)}
function selectMapUnit(group){if(!gameRunning||activeSide!=='PLAYER'||phaseIndex!==0)return;const p=placementLog.find(x=>x.id===group.dataset.placementId);if(!p||p.side!=='PLAYER')return;if(activatedThisPhase.has(p.id)){$('#resultsHint').textContent=p.label+'은 이번 Phase에 이미 활성화되었습니다';return}selectedPlacement={existing:p};document.querySelectorAll('.manual-placement.selected').forEach(x=>x.classList.remove('selected'));group.classList.add('selected');showMoveGuide(p);$('#resultsHint').textContent=p.label+' · 최대 이동 '+p.speed+'″'}
new MutationObserver(()=>{mountUpgradePickers();decorateRosters()}).observe(document.querySelector('.battleboard'),{childList:true,subtree:true});
new MutationObserver(()=>{if(placementMode)return;$('#resultsHint').textContent=$('#resultsTitle').textContent==='전투 리플레이'?'로스터':'리플레이'}).observe($('#resultsTitle'),{childList:true,characterData:true,subtree:true});
document.addEventListener('keydown',e=>{if(e.key!=='Enter'||e.isComposing)return;const target=e.target;if(target.closest('#chatForm')||target.matches('button,select,textarea'))return;e.preventDefault();if(gameRunning&&activeSide==='PLAYER')passTurn();else if(!gameRunning)toggleGame()});
const unitBubble=document.createElement('div');unitBubble.id='unitBubble';unitBubble.className='unit-bubble';unitBubble.hidden=true;$('#mapWrap').append(unitBubble);const mapZoomToggle=document.createElement('button');mapZoomToggle.id='mapZoomToggle';mapZoomToggle.className='map-zoom-toggle';mapZoomToggle.type='button';mapZoomToggle.title='지도 확대';mapZoomToggle.setAttribute('aria-label','지도 확대');document.querySelector('.map-card>header').append(mapZoomToggle);mapZoomToggle.addEventListener('click',toggleMapFocus);$('#mapWrap').addEventListener('mouseover',showUnitBubble);$('#mapWrap').addEventListener('mouseout',hideUnitBubble);$('#mapWrap').addEventListener('click',placeSelected);document.addEventListener('click',e=>{const row=e.target.closest('.squad[data-placement-key]');if(row)selectPlacement(row)});
document.addEventListener('click',e=>{const unit=e.target.closest('.manual-placement[data-placement-id]');if(unit){e.stopPropagation();selectMapUnit(unit)}});
$('.warning').textContent='공식 미션 점수와 시뮬레이션용 지형 프리셋을 연결했습니다. 지형 LOS·엄폐·고저차 판정은 TODO입니다.';$('#terrain').textContent=BATTLEFIELD.deployment+' · '+BATTLEFIELD.terrain.join(' · ');$('#run').addEventListener('click',resetGame);$('#gameToggle').addEventListener('click',toggleGame);$('#phasePass').addEventListener('click',passTurn);$('#points').addEventListener('change',render);$('#missionSelect').addEventListener('change',()=>{updateMissionLayout();render()});$('#chatToggle').addEventListener('click',()=>setChat(!$('#strategyChat').classList.contains('open')));$('#chatClose').addEventListener('click',()=>setChat(false));$('#chatForm').addEventListener('submit',submitChat);loadState();loadRosterStates();loadChatHistory();updateMissionLayout();render();decorateRosters();updatePhaseUi();
$('#resultsHint').textContent='리플레이';

