import { UNITS, ROSTERS, MISSIONS } from './data.js';
export function mulberry32(seed){return function(){let t=seed+=0x6D2B79F5;t=Math.imul(t^t>>>15,t|1);t^=t+Math.imul(t^t>>>7,t|61);return((t^t>>>14)>>>0)/4294967296}}
const d6=r=>1+Math.floor(r()*6);function surgeRoll(x,r){if(!x)return 0;const p=x.includes('+')?Number(x.split('+')[1]):0;return(x.startsWith('D3')?1+Math.floor(r()*3):d6(r))+p}
const SUPPLY_PROFILES={marine:[[3,0],[6,1],[9,2]],marauder:[[1,0],[2,1],[4,2]],goliath:[[1,2]],zergling:[[6,0],[12,1],[18,2]],roach:[[1,0],[3,1]],hydralisk:[[1,1],[2,2],[4,3]],zealot:[[1,1],[3,2]],stalker:[[1,1],[2,2]],adept:[[2,0],[4,1]]};
export function currentSupply(u){if(u.destroyed||!u.models)return 0;const p=SUPPLY_PROFILES[u.id]||[[u.initialModels||u.models,u.supply||0]];return(p.find(([max])=>u.models<=max)||p.at(-1))[1]}
export function makeUnit(id,side,x,o={}){const d=UNITS[id];if(!d)throw Error(`Unknown unit: ${id}`);const models=o.models??d.models??1;return{...structuredClone(d),...o,side,x,models,initialModels:models,wounds:0,destroyed:false,roundBonus:{precision:0,range:0,speed:0}}}
export const distance=(a,b)=>Math.abs(a.x-b.x);export function moveToward(u,t){const gap=distance(u,t),speed=u.speed+(u.roundBonus?.speed||0),travel=Math.max(0,Math.min(speed,gap-1));u.x+=Math.sign(t.x-u.x)*travel;return travel}
export function attack(a,d,r,log=[]){const w=a.weapon,dist=distance(a,d),range=w.range+(a.roundBonus?.range||0);if(a.destroyed||d.destroyed||dist>range)return{legal:false,reason:'out of range'};const beforeSupply=currentSupply(d),rolls=Array.from({length:a.models*w.roa},()=>d6(r)),rawHits=rolls.filter(v=>v>=w.hit).length,precision=Math.min(a.roundBonus?.precision||0,rolls.length-rawHits),hits=rawHits+precision,matching=w.surge.some(t=>d.tags.includes(t)),surge=matching?Math.min(hits,surgeRoll(w.surgeDie,r)):0,armourRolls=Array.from({length:hits-surge},()=>d6(r));let damageDice=surge+armourRolls.filter(v=>v<d.armour).length;const evadeEligible=dist<=1&&w.range>1,evadeRolls=evadeEligible?Array.from({length:damageDice},()=>d6(r)):[];damageDice-=evadeRolls.filter(v=>v>=d.evade).length;const damage=damageDice*w.damage;d.wounds+=damage;let casualties=0;while(d.models>0&&d.wounds>=d.hp){d.wounds-=d.hp;d.models--;casualties++}if(!d.models){d.destroyed=true;d.wounds=0}const supplyDestroyed=Math.max(0,beforeSupply-currentSupply(d)),e={legal:true,type:'attack',attacker:a.label||a.name,attackerId:a.instanceId,attackerX:a.x,defender:d.label||d.name,defenderId:d.instanceId,defenderX:d.x,weapon:w.name,dist,rolls,hits,precision,surge,armourRolls,evadeRolls,damage,casualties,supplyDestroyed,remaining:d.models};log.push(e);a.roundBonus.precision=0;a.roundBonus.range=0;return e}
function act(u,t,r,log){const range=u.weapon.range+(u.roundBonus?.range||0);if(distance(u,t)<=range)return attack(u,t,r,log);const from=u.x,moved=moveToward(u,t),e={type:'move',unit:u.label||u.name,unitId:u.instanceId,models:u.models,from,to:u.x,distance:moved};log.push(e);return e}
export function simulate(o={}){const{a='marine',b='zergling',seed=1,maxRounds=20,startDistance=24}=o,r=mulberry32(+seed),left=makeUnit(a,'A',0),right=makeUnit(b,'B',+startDistance),log=[];for(let round=1;round<=maxRounds&&!left.destroyed&&!right.destroyed;round++){log.push({type:'round',round});if(distance(left,right)>left.weapon.range)act(left,right,r,log);if(!right.destroyed&&distance(right,left)>right.weapon.range)act(right,left,r,log);if(!left.destroyed&&distance(left,right)<=left.weapon.range)attack(left,right,r,log);if(!right.destroyed&&distance(right,left)<=right.weapon.range)attack(right,left,r,log)}return{winner:left.destroyed?(right.destroyed?'draw':'B'):(right.destroyed?'A':'draw'),left,right,log,rounds:log.filter(e=>e.type==='round').length}}
export function runBatch(o={}){const games=+o.games||100,wins={A:0,B:0,draw:0};let rounds=0;for(let i=0;i<games;i++){const r=simulate({...o,seed:(+o.seed||1)+i});wins[r.winner]++;rounds+=r.rounds}return{games,wins,winRates:{A:wins.A/games,B:wins.B/games,draw:wins.draw/games},averageRounds:rounds/games}}
const buildArmy=(roster,side,x)=>roster.entries.map((e,i)=>makeUnit(e.unit,side,x,{...e,instanceId:`${side}-${i}`})),living=a=>a.filter(u=>!u.destroyed);function nearest(u,a){return living(a).sort((x,y)=>distance(u,x)-distance(u,y)||(x.models*x.hp+x.wounds)-(y.models*y.hp+y.wounds))[0]}
function prepareCards(army,race,log){for(const u of living(army))u.roundBonus={precision:0,range:0,speed:0};if(race==='Zerg'){const hydra=living(army).find(u=>u.id==='hydralisk'),ling=living(army).find(u=>u.id==='zergling');if(hydra){hydra.roundBonus.precision=1;log.push({type:'card',card:'Hydralisk Den',target:hydra.label,effect:'PRECISION (1)'})}if(ling){ling.roundBonus.precision=2;log.push({type:'card',card:'Spawning Pool',target:ling.label,effect:'PRECISION (2) on melee'})}}else if(race==='Terran'){const bio=living(army).find(u=>u.tags.includes('Biological')),mech=living(army).find(u=>u.tags.includes('Mechanical'));if(bio){bio.roundBonus.speed=2;log.push({type:'card',card:'Barracks',target:bio.label,effect:'+2 Move'})}if(mech&&mech.wounds){const healed=Math.min(2,mech.wounds);mech.wounds-=healed;log.push({type:'card',card:'Factory',target:mech.label,effect:`HEAL (${healed})`})}}else{const zealot=living(army).find(u=>u.id==='zealot'),stalker=living(army).find(u=>u.id==='stalker');if(zealot){zealot.roundBonus.precision=2;log.push({type:'card',card:'Gateway',target:zealot.label,effect:'PRECISION (2) on melee'})}if(stalker){stalker.roundBonus.range=4;log.push({type:'card',card:'Twilight Council',target:stalker.label,effect:'+4 Range'})}}
}
const MARKERS=[9,18,27,36,45];function markerControl(left,right,previous){return MARKERS.map((x,i)=>{const a=living(left).filter(u=>Math.abs(u.x-x)<=3).reduce((n,u)=>n+currentSupply(u),0),b=living(right).filter(u=>Math.abs(u.x-x)<=3).reduce((n,u)=>n+currentSupply(u),0),controller=a>b?'A':b>a?'B':null;return{id:i+1,x,a,b,controller,previous:previous?.[i]?.controller||null}})}
function addBaseVp(score,roundDestroyed){score.A+=roundDestroyed.A;score.B+=roundDestroyed.B}
function scoreMission(mission,round,markers,score,roundDestroyed,left,right,log,activated){
 addBaseVp(score,roundDestroyed);
 if(mission==='frontlines'&&round>=2)for(const m of markers)if(m.controller){score[m.controller]+=1;if(m.previous&&m.previous!==m.controller)score[m.controller]+=2}
 if(mission==='hold'&&round>=2)for(const m of markers)if(m.controller){const friendly=m.controller==='A'?[1,3].includes(m.id):[2,4].includes(m.id);score[m.controller]+=friendly||m.id===5?1:2}
 if(mission==='gather'&&round>=2)for(const m of markers)if(m.controller){const enemy=m.controller==='A'?[2,4].includes(m.id):[1,3].includes(m.id);if(enemy)score[m.controller]+=2}
 if(mission==='supply'){const id=round===5?5:1+Math.floor(activated.random()*4);activated.ids.add(id);for(const m of markers)if(activated.ids.has(m.id)&&m.controller){score[m.controller]+=round;activated.ids.delete(m.id)}}
 if(mission==='divide'){for(const side of ['A','B']){const army=side==='A'?left:right,enemy=side==='A'?right:left;for(const [lo,hi] of [[0,13.5],[13.5,27],[27,40.5],[40.5,54]]){const own=living(army).filter(u=>u.x>=lo&&u.x<=hi).reduce((n,u)=>n+currentSupply(u),0),opp=living(enemy).filter(u=>u.x>=lo&&u.x<=hi).reduce((n,u)=>n+currentSupply(u),0);if(own>opp)score[side]++}if(markers[4]?.controller===side)score[side]+=2}}
 log.push({type:'score',mission,round,score:{...score},destroyed:{...roundDestroyed},markers:markers.map(m=>m.controller||'-'),activeMarkers:[...activated.ids]})
}
export function simulateRoster(o={}){const{opponent='terran',seed=1,startDistance=54}=o,mission=o.mission||'frontlines',profile=MISSIONS[mission]||MISSIONS.frontlines,maxRounds=Math.min(o.maxRounds||profile.rounds,profile.rounds),r=mulberry32(+seed),leftRoster=o.leftRoster||ROSTERS.zerg,left=buildArmy(leftRoster,'A',0),enemyRoster=o.enemyRoster||ROSTERS[opponent]||ROSTERS.terran,right=buildArmy(enemyRoster,'B',+startDistance),log=[],score={A:0,B:0},activated={ids:new Set,random:r};let previousMarkers=null,endedBy='round-limit';for(let round=1;round<=maxRounds&&living(left).length&&living(right).length;round++){log.push({type:'round',round});prepareCards(left,leftRoster.race,log);prepareCards(right,enemyRoster.race,log);const roundDestroyed={A:0,B:0};for(const u of living(left)){const t=nearest(u,right);if(t&&distance(u,t)>u.weapon.range+(u.roundBonus.range||0))act(u,t,r,log)}for(const u of living(right)){const t=nearest(u,left);if(t&&distance(u,t)>u.weapon.range+(u.roundBonus.range||0))act(u,t,r,log)}const first=round%2?[left,right]:[right,left],order=[];for(let i=0;i<Math.max(first[0].length,first[1].length);i++){if(first[0][i])order.push(first[0][i]);if(first[1][i])order.push(first[1][i])}for(const u of order){if(u.destroyed)continue;const enemies=u.side==='A'?right:left,t=nearest(u,enemies);if(t&&distance(u,t)<=u.weapon.range+(u.roundBonus.range||0)){const e=attack(u,t,r,log);roundDestroyed[u.side]+=e.supplyDestroyed||0}}const markers=markerControl(left,right,previousMarkers);scoreMission(mission,round,markers,score,roundDestroyed,left,right,log,activated);previousMarkers=markers;if(Math.abs(score.A-score.B)>=profile.lead){endedBy='vp-lead';break}}if(!living(left).length||!living(right).length)endedBy='army-destroyed';const winner=score.A===score.B?(living(left).length===living(right).length?'draw':living(left).length>living(right).length?'A':'B'):score.A>score.B?'A':'B';return{winner,left,right,log,score,endedBy,mission,rounds:log.filter(e=>e.type==='round').length}}
export function runRosterBatch(o={}){const games=+o.games||100,wins={A:0,B:0,draw:0};let rounds=0,aSurvivors=0,bSurvivors=0,aVp=0,bVp=0;for(let i=0;i<games;i++){const r=simulateRoster({...o,seed:(+o.seed||1)+i});wins[r.winner]++;rounds+=r.rounds;aVp+=r.score.A;bVp+=r.score.B;aSurvivors+=living(r.left).reduce((n,u)=>n+u.models,0);bSurvivors+=living(r.right).reduce((n,u)=>n+u.models,0)}return{games,wins,winRates:{A:wins.A/games,B:wins.B/games,draw:wins.draw/games},averageRounds:rounds/games,averageVp:{A:aVp/games,B:bVp/games},averageSurvivors:{A:aSurvivors/games,B:bSurvivors/games}}}

